entrega2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')), # modifique esta linha
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path, re_path

from . import views

app_name = 'posts'
urlpatterns = [
    # path('', views.PostListView.as_view(), name='index'),
    # path('create/', views.PostCreateView.as_view() ,name='create'),
    # path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    # path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    # path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('', views.list_posts, name='index'),
    path('list_categories/', views.list_categories, name='list_categories'),
    path('category/<int:category_id>/', views.detail_category, name='detail_category'),
    path('create/', views.create_post ,name='create'),
    path('search/', views.search_posts ,name='search'),
    path('update/<int:post_id>/', views.update_post, name='update'),
    path('delete/<int:post_id>/', views.delete_post, name='delete'),
    path('<int:post_id>/', views.detail_post, name='detail'),
    path('<int:post_id>/review/', views.create_review, name='review'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), # adicione esta linha
    path('', views.index, name='index'),
]

posts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
from django.db import models

class Post(models.Model):
    name = models.CharField(max_length=255)
    data = models.DateTimeField(auto_now=True)
    conteudo = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.name} ({self.data})'

class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    data = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    name = models.CharField(max_length=255)
    descricao = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name}'

staticpages/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Post(models.Model):
    titulo = models.CharField(max_length=255)
    conteudo = models.CharField(max_length=255)
    data = models.DateTimeField()
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name} ({self.release_year})'

posts/forms.py
from django import forms
from .models import Post, Review
from django.forms import ModelForm

'''class PostForm(forms.Form):
    name = forms.CharField(label='Título', max_length=100)
    data = forms.IntegerField(label='Data de Publicação',
                                      min_value=1888)
    conteudo = forms.CharField(label='Conteúdo', max_length=5000)
'''
class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'conteudo',
        ]
        labels = {
            'name': 'Título',
            'conteudo': 'Conteúdo',
        }

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Resenha',
        }

posts/views.py
from django.shortcuts import render, get_object_or_404
import unidecode 
# Create your views here.
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .temp_data import post_data
from .models import Post, Review, Category
from django.views import generic
from .forms import PostForm, ReviewForm


'''class PostListView(generic.ListView):
    model = Post
    template_name = 'posts/index.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'

class PostCreateView(generic.CreateView):
    model = Post
    template_name = 'posts/create.html'
    form_class = PostForm
    success_url = reverse_lazy('posts:index')
    
class PostUpdateView(generic.UpdateView):
    model = Post
    template_name = 'posts/update.html'
    fields = ['name', 'conteudo']
    reverse_lazy('posts:index')

class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'posts/delete.html'
    success_url = reverse_lazy('posts:index')'''

def search_posts(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        post_list = Post.objects.filter(name__icontains=search_term)
        context = {"post_list": post_list}
    return render(request, 'posts/search.html', context)

def list_posts(request):
    post_list = Post.objects.all()
    context = {'post_list': post_list}
    return render(request, 'posts/index.html', context)

def detail_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post}
    return render(request, 'posts/detail.html', context)

def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post_name = form.cleaned_data['name']
            #post_data = form.cleaned_data['data']
            post_conteudo = form.cleaned_data['conteudo']
            post = Post(name=post_name,
                        conteudo=post_conteudo)
            post.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post.id, )))
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'posts/create.html', context)

def update_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post.name = form.cleaned_data['name']
            post.conteudo = form.cleaned_data['conteudo']
            post.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post.id, )))
    else:
        form = PostForm(
            initial={
                'name': post.name,
                'conteudo': post.conteudo
            })
    context = {'post': post, 'form': form}
    return render(request, 'posts/update.html', context)


def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        post.delete()
        return HttpResponseRedirect(reverse('posts:index'))

    context = {'post': post}
    return render(request, 'posts/delete.html', context)

def create_review(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review_author = form.cleaned_data['author']
            review_text = form.cleaned_data['text']
            review = Review(author=review_author,
                            text=review_text,
                            post=post)
            review.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post_id, )))
    else:
        form = ReviewForm()
    context = {'form': form, 'post': post}
    return render(request, 'posts/review.html', context)

def list_categories(request):
    category_list = Category.objects.all()
    context = {'category_list': category_list}
    return render(request, 'posts/list_categories.html', context)

def detail_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    context = {'category': category}
    return render(request, 'posts/category_detail.html', context)

staticpages/views.py
from django.shortcuts import render

def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)

def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

posts/templates/posts/category_detail.html
{% extends 'base.html' %}

{% block title %}
{{ category.name }}
{% endblock title %}

{% block content %}
<h2>{{ category.descricao }}</h2>
<section>
    <ul>
        {% for post in category.posts.all %}
            <article class="card">
                <a href="{% url 'posts:detail' post.id %}">{{ post.name }} ({{ post.data|date:"m/Y" }})</a>
            </article>
        {% endfor %}
    </ul>
    <hr>
</section>

{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Post</h2>
<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

<!--<h2>Inserir Novo Post</h2>
<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}
    <p>
        <label for="id_name">Título:</label>
        <input type="text" name="name" id="id_name" />
    </p>
    <p>
        <label for="id_data">Data de Publicação:</label>
        <input type="number" name="data" id="id_data" />
    </p>

    <p>
        <label for="id_conteudo">Conteúdo do Post:</label>
        <input type="text" name="conteudo" id="id_conteudo" />
    </p>
    <button type="submit">Criar</button>
</form>-->

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o post "{{ post.name }} ({{ post.data|date }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.name }} ({{ post.data }}
{% endblock title %}

{% block content %}
<h2>Resenha sobre o restaurante {{ post.name }}</h2>

<section class="dados-de-filme">
    <ul>
        <li><b>Data de Publicação:</b> {{ post.data }} </li><br>
        <li><b>Incluso nas categorias: </b></li>
        <ul>
            {% for category in post.category_set.all %}
                <li> <a href="{% url 'posts:detail_category' category.id %}"> {{ category }}</a> </li>
            {% endfor %}
        </ul><br>
        <li><b>Resenha:</b> {{post.conteudo}}</li>
        <li><a href="{% url 'posts:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'posts:delete' post.id %}">Apagar</a></li>
    </ul>
    
</section>
<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if post.review_set.all %}
            {% for review in post.review_set.all %}
                <figure>
                    <blockquote>
                        "{{ review.text }}"
                    </blockquote>
                    <figcaption>- {{ review.author }} {{ review.data|date:"m/Y" }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhuma resenha para este filme.</p>
        {% endif %}
    </ul>
    <hr>

    <a href="{% url 'posts:review' post.id %}"><button>Crie sua Resenha</button></a>
</section>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Posts</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'posts:search' %}">Buscar Posts</a></p>
    <p>Não encontrou o post? <a href="{% url 'posts:create' %}">Adicionar Novo Post</a></p>
</section>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'posts:detail' post.id %}">{{ post.name }} ({{ post.data|date:"m/Y" }})</a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/list_categories.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos as Categorias</h2>
{% if category_list %}
<section class="lista-de-cards">
    {% for category in category_list %}
    <article class="card">
        <a href="{% url 'posts:detail_category' category.id %}">{{ category.name }}</a>
        <p>{{category.descricao}}</p> 
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/review.html
{% extends 'base.html' %}

{% block content %}
<h2>Resenhar Post {{ post.name }} ({{post.data|date:"m/Y"}})</h2>

<form action="{% url 'posts:review' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Resenha</button>
</form>

<p><a href="{% url 'posts:detail' post.id %}">Voltar para a página do post</a></p>
{% endblock content %}

posts/templates/posts/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Post por Nome</h2>
<form action="{% url 'posts:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'posts:detail' forloop.counter %}">{{ post.name }} ({{ post.data|date }})</a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post para a busca.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}

<h2>Atualizar Dados do Post {{ post.name }}({{ post.data|date:"m/Y"}})</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

<!--
<h2>Atualizar Dados do Post {{ post.name }} ({{ post.data}})</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    <p>
        <label for="id_name">Título:</label>
        <input type="text" name="name" id="id_name" value="{{ post.name }}" />
    </p>
    <p>
        <label for=" id_data">Data de Publicação:</label>
        <input type="number" name="data" id="id_data" value="{{ post.data }}" />
    </p>
    <p>
        <label for=" id_conteudo">Conteúdo:</label>
        <input type="text" name="conteudo" id="id_conteudo" value="{{ post.conteudo }}" />
    </p>
    <button type="submit">Atualizar</button>
</form>-->

{% endblock content %}

staticpages/templates/base.html
{% load static %} <!-- adicione esta linha -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Watch that film!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha -->
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'imagem.svg' %}" width="100px"> </a> <!-- adicione esta linha -->
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'posts:index' %}">Restaurantes</a></li> 
                <li><a href="{% url 'posts:list_categories' %}">Categorias</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
<p>Essa página foi criada para aplicar conceitos aprendidos sobre back-end, utilizando Django, para a disciplina PMR-3304</p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Blog</i></h1>
<p>A página de blogs de restaurantes</p>
{% endblock content %}